// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }
import { ClerkProvider } from '@clerk/nextjs'
import {Inter} from "next/font/google"

import '../globals.css;'

// type RootLayout = {
//     ClerkProvider: typeof ClerkProvider;
// <html lang="en">

// <body className={inter.className}>

//            {children}
           
// </body>

//         </html>

//   };

export const metadate = {
    title: 'Threads',
    description: 'A Next.js 13 Meta Thread Application'
}

const inter = Inter({subsets: ["latin"]})

export default function RootLayout({
    children
} : {
    children: React.ReactNode
}) {
    return (
      <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} bg-dark-1`}>
          {children}
          </body>
      </html>
    </ClerkProvider>
    )
}